// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIwkIWZFxceqM06wSQZYc7DSIW1p5khQU',
    appId: '1:115188283766:web:b3ebbee4e3d5149ff5e257',
    messagingSenderId: '115188283766',
    projectId: 'medicare1-9ec97',
    authDomain: 'medicare1-9ec97.firebaseapp.com',
    storageBucket: 'medicare1-9ec97.firebasestorage.app',
    measurementId: 'G-8BZB4TRQDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXaQfSGy6DGt6LIXS0raWxYy2gIuV-Zmw',
    appId: '1:115188283766:android:945bd8254d246ebff5e257',
    messagingSenderId: '115188283766',
    projectId: 'medicare1-9ec97',
    storageBucket: 'medicare1-9ec97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiPi9oTP3XA7M4M0e4GnTd2fAlSEaof4Y',
    appId: '1:115188283766:ios:67d940c170071fa7f5e257',
    messagingSenderId: '115188283766',
    projectId: 'medicare1-9ec97',
    storageBucket: 'medicare1-9ec97.firebasestorage.app',
    iosBundleId: 'com.example.medicare1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiPi9oTP3XA7M4M0e4GnTd2fAlSEaof4Y',
    appId: '1:115188283766:ios:67d940c170071fa7f5e257',
    messagingSenderId: '115188283766',
    projectId: 'medicare1-9ec97',
    storageBucket: 'medicare1-9ec97.firebasestorage.app',
    iosBundleId: 'com.example.medicare1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIwkIWZFxceqM06wSQZYc7DSIW1p5khQU',
    appId: '1:115188283766:web:e83c7368b08344f3f5e257',
    messagingSenderId: '115188283766',
    projectId: 'medicare1-9ec97',
    authDomain: 'medicare1-9ec97.firebaseapp.com',
    storageBucket: 'medicare1-9ec97.firebasestorage.app',
    measurementId: 'G-6N175C5S95',
  );
}
